name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: [self-hosted, unicorn]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Git LFS
        run: git lfs install
      - name: Pull LFS files
        run: git lfs pull
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: DOCUSAURUS_IGNORE_SSG_WARNINGS=true yarn build
